<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="manifest" href="manifest.json" />
<link rel="apple-touch-icon" sizes="57x57" href="/images/icons/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/images/icons/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/images/icons/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/images/icons/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/images/icons/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/images/icons/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/images/icons/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/images/icons/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/images/icons/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/images/icons/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/images/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/images/icons/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/images/icons/favicon-16x16.png">
<meta name="apple-mobile-web-app-status-bar" content="#17a2b8" />
<meta name="theme-color" content="#db4938" />
<script src="/assets/js/jquery-3.5.1.js"></script>
<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
<script src="/assets/js/bootstrap.min.js"></script>
<script type="text/javascript"  src="/assets/js/theme.js"></script>
<link href="/assets/css/theme.css" rel="stylesheet" />
<script type="text/javascript"  src="/assets/js/app.js?ver=031"></script>
<title><?=$title?></title>
</head>
<body>
	<div class="navigation-wrap bg-light start-header start-style">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<nav class="navbar navbar-expand-md navbar-light">
					
						<a class="navbar-brand rounded d-block" href="/home" ><img src="/images/logo.png" alt=""></a>	
						
						<!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button> -->
						
						<div class="collapse navbar-collapse" id="navbarSupportedContent">
							<ul class="navbar-nav ml-auto py-4 py-md-0">
								<!-- <li class="pl-4 pl-md-0 ml-0 ml-md-4">
									<a class="nav-link" href="/home">Home</a>
								</li> -->
								<!-- <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
									<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
									<div class="dropdown-menu">
										<a class="dropdown-item" href="#">Users</a>
										<a class="dropdown-item" href="#">Report</a>
									</div>
								</li> -->
							</ul>
						</div>
						
					</nav>		
				</div>
			</div>
		</div>
	</div>

	<div class="app">

		<div class="container">
			<div class="row justify-content-center">
				<button type="button" class="add-pwa btn btn-secondary">Add to home screen</button>
			</div>
			<?=$content?>
		</div>
	</div>
	<br>
<footer  class="text-center">&copy; <?=date("Y")?> Copyright: Faheem Seedat
  </footer >

</body>
<script>
        if ("serviceWorker" in navigator) {
    window.addEventListener("load", function() {
      navigator.serviceWorker
        .register("/serviceWorker.js")
        .then(res => console.log("service worker registered"))
        .catch(err => console.log("service worker not registered", err))
    })
  }

	let deferredPrompt;
	const addBtn = document.querySelector('.add-pwa');
	addBtn.style.display = 'none';
</script>
</html>